repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-merge-conflict    # Check for files that contain merge conflict strings
      - id: trailing-whitespace     # This hook trims trailing whitespace
      - id: end-of-file-fixer       # Ensures that a file is either empty, or ends with one newline
      - id: detect-private-key      # Detects the presence of private keys
      - id: check-json              # This hook checks json files for parseable syntax
      - id: check-yaml              # This hook checks yaml files for parseable syntax
      - id: detect-aws-credentials  # Detects *your* aws credentials from the aws cli credentials file
        args:
          - --allow-missing-credentials

  # please refer to: https://github.com/antonbabenko/pre-commit-terraform#available-hooks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.71.0
    hooks:
      - id: terraform_fmt       # Automatically run "terraform fmt" on all terraform code
      - id: terraform_tflint    # Automatically run tflint on all terraform code
      - id: terraform_docs      # Automatically run terraform_docs when its pattern available in README.md

  # Gitleaks is a SAST tool for detecting and preventing hardcoded secrets like passwords, api keys, and tokens in git repos
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.8.4
    hooks:
      - id: gitleaks

#Commitizen is a CLI tools to validate commit message following semantic commit standard
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.27.0
    hooks:
      - id: commitizen
        stages: [ commit-msg ]
